### ISSUE TITLE
how much memory stay in the gpu while finetuning the conv-BN-scale ohem of your code?

### ISSUE THREAD

**Issue by 646677064** [Eniac-Xie/faster-rcnn-resnet#10]
I tried to finetune the conv-BN-scale ohem of your code, the memory of my gpu was 11579MiB / 12238MiB . It occured to corrupt down for  several times (out of memory ).It would dangerous always,haha
   Would you give more advise? the batchsize would not work for ohem

**Comment by lcwbupt** [comment]
i meet the same problem that out of memory when traing with ohem. My gpu was 1080 ti with 11GB

**Comment by Eniac-Xie** [comment]
Hi, A GPU with 12GB memory will be OK, @646677064  maybe you can check if there is other program on your GPU.

Another way to reduce the memory use is to use small RPN_POST_NMS_TOP_N in faster_rcnn_end2end_ohem.yml, it will lead to lower performance, so do not set the RPN_POST_NMS_TOP_N too small

**Comment by 646677064** [comment]
@Eniac-Xie  Yes, so I setted  RPN_POST_NMS_TOP_N=**1000**, gpu ran out of memory,while RPN_POST_NMS_TOP_N=**300** lead to lower performance as you said just now

**Comment by hzh8311** [comment]
At paper _R-FCN: Object Detection via Region-based Fully Convolutional Networks_, it trained faster rcnn with resnet with 300 ROIs and OHEM, and gained approximately same performance. Why performance dropped here?

**Comment by twmht** [comment]
Does 300 rois work for 11GB card?
