### ISSUE TITLE
How much video memory does training need?

### ISSUE THREAD

**Issue by jwnsu** [Eniac-Xie/faster-rcnn-resnet#3]
I tried with Nvidia 1070 card and it's out of video memory. How much memory does training require?

New 1080 ti card has 11GB, just to check whether 11GB is big enough.

**Comment by Eniac-Xie** [comment]
12GB will be ok. Try to use small RPN_POST_NMS_TOP_N in experiments/cfgs/faster_rcnn_end2end_ohem.yml, but it may lead to low accuracy.

**Comment by jwnsu** [comment]
new 1080Ti only has 11GB, while Titan X has 12GB. Wondering whether the 1GB difference will be a critical one. We can run Resnet-50 with 8GB. 101-Resnet testing from this repository only takes 5GB.

**Comment by Eniac-Xie** [comment]
faster_rcnn_end2end_ohem will use 10010MiB GPU memory while training.
