### ISSUE TITLE
I woder if merge_bn_scale speed up the testing time. 

### ISSUE THREAD

**Issue by CK2Github** [Eniac-Xie/faster-rcnn-resnet#9]

**Comment by 646677064** [comment]
@CK2Github  I tried R-FCN + ResNet-101,why  R-FCn-ohem take 5g of the gpu memory ,but the faster-rcnn+resnet-101 take 11g of the gpu memory

**Comment by CK2Github** [comment]
@646677064 It seems that the way these two algorithms implement OHEM is different ,faster RCNN +resnet+ohem copy  a read only network to implement OHEM.   I am not sure ,you can check the difference between these two networks .

**Comment by Eniac-Xie** [comment]
@CK2Github Yes, it is caused by OHEM
